const invoke=window.__TAURI__&&window.__TAURI__.core&&window.__TAURI__.core.invoke;
const $=id=>document.getElementById(id),fields=["offsetX","offsetY","weaponRotation","armRotation","frontArmFrame","backArmFrame"],baseFields=["baseOffsetX","baseOffsetY"];
let item,currentPath,facing=1,aim=0,assets={},generatedWeapon=null,itemPartOffset=[0,0],itemPartName="middle",itemPartOffsetSource="baseOffset",humanoidConfig={};
const canvas=$("scene"),ctx=canvas.getContext("2d"),scene={width:760,height:620};
// Starbound 贴图坐标为 8 px / 世界单位，因此 0.125 单位恰为 1 个游戏像素。
// 预览将每个贴图像素放大 4 倍，所以 1 单位在画布上是 8 * 4 = 32 像素。
const PoseModel={scale:4,unitPixels:32,armBase:{x:0,y:0},handReach:12};

const messages={
  "zh-CN":{language:"语言",root:"Starbound 根目录",activeitem:"ActiveItem 文件",browse:"浏览…",character:"角色",humanTemplate:"人类模板",stance:"姿势（Stance）",baseOffsetX:"baseOffset X（0.125 = 1 游戏像素）",baseOffsetY:"baseOffset Y（0.125 = 1 游戏像素）",weaponOffsetX:"weaponOffset X（0.125 = 1 游戏像素）",weaponOffsetY:"weaponOffset Y（0.125 = 1 游戏像素）",weaponRotation:"weaponRotation°",armRotation:"armRotation°",frontArmFrame:"前臂帧",backArmFrame:"后臂帧",showGuides:"显示锚点与瞄准线",baseLoading:"贴图基础偏移：读取中…",flip:"切换左右朝向",canvasLabel:"持物姿势预览",canvasHelp:"在画布任意处拖动可修改瞄准角。蓝线为瞄准方向，橙点为手部锚点。",itemPlaceholder:"C:\\...\\weapon.activeitem",statusInit:"正在初始化…",selectItem:"请选择 ActiveItem 文件",rootSelected:"已选择 Starbound 根目录",loaded:"已加载 {count} 个 stance；{kind}",randomTemplate:"随机模板已组合",fixedTemplate:"固定模板已加载",baseInfo:"贴图基础偏移来源：{source}；预览值：[{value}]",bodyOrigin:"身体原点"},
  en:{language:"Language",root:"Starbound Root Directory",activeitem:"ActiveItem File",browse:"Browse…",character:"Character",humanTemplate:"Human Template",stance:"Stance",baseOffsetX:"baseOffset X (0.125 = 1 game pixel)",baseOffsetY:"baseOffset Y (0.125 = 1 game pixel)",weaponOffsetX:"weaponOffset X (0.125 = 1 game pixel)",weaponOffsetY:"weaponOffset Y (0.125 = 1 game pixel)",weaponRotation:"weaponRotation°",armRotation:"armRotation°",frontArmFrame:"Front arm frame",backArmFrame:"Back arm frame",showGuides:"Show anchors and aim line",baseLoading:"Sprite base offset: loading…",flip:"Flip facing",canvasLabel:"Held-item pose preview",canvasHelp:"Drag anywhere on the canvas to change the aim angle. Blue is the aim direction; orange is the hand anchor.",itemPlaceholder:"C:\\...\\weapon.activeitem",statusInit:"Initializing…",selectItem:"Choose an ActiveItem file",rootSelected:"Starbound root selected",loaded:"Loaded {count} stance(s); {kind}",randomTemplate:"random template assembled",fixedTemplate:"fixed template loaded",baseInfo:"Sprite base-offset source: {source}; preview: [{value}]",bodyOrigin:"Body origin"}
};
Object.assign(messages["zh-CN"],{avian:"鸟人（Avian）",apex:"猿人（Apex）",floran:"叶族（Floran）",glitch:"机器人（Glitch）",hylotl:"鱼人（Hylotl）"});
Object.assign(messages.en,{avian:"Avian",apex:"Apex",floran:"Floran",glitch:"Glitch",hylotl:"Hylotl"});
let uiLanguage=(()=>{try{return localStorage.getItem("itemPoseEditor.language")==="en"?"en":"zh-CN"}catch(_){return"zh-CN"}})(),statusState={key:"statusInit",values:{},error:false};
function t(key,values={}){return(messages[uiLanguage][key]||messages["zh-CN"][key]||key).replace(/\{(\w+)\}/g,(_,name)=>String(values[name]===undefined?"":values[name]))}
function setBaseInfo(){ $("baseInfo").textContent=t("baseInfo",{source:itemPartOffsetSource==="baseOffset"?"baseOffset":"animationCustom",value:itemPartOffset.join(", ")}) }
function statusKey(key,values={},error=false){statusState={key,values,error};status(t(key,values),error,true)}
function applyLanguage(){document.documentElement.lang=uiLanguage;document.title="Starbound Item Pose Editor";document.querySelectorAll("[data-i18n]").forEach(node=>node.textContent=t(node.dataset.i18n));document.querySelectorAll("[data-i18n-placeholder]").forEach(node=>node.placeholder=t(node.dataset.i18nPlaceholder));document.querySelectorAll("[data-i18n-aria]").forEach(node=>node.setAttribute("aria-label",t(node.dataset.i18nAria)));$("language").value=uiLanguage;if(statusState.key)status(t(statusState.key,statusState.values),statusState.error,true);if(item)setBaseInfo();render()}

function status(message,error=false,preserveState=false){if(!preserveState)statusState={key:null,values:{},error};$("status").textContent=message;$("status").style.color=error?"#ff9292":"#9fb1c9"}
function syncCanvas(){const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;scene.width=rect.width;scene.height=rect.height;const width=Math.round(scene.width*dpr),height=Math.round(scene.height*dpr);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false}
function stance(){return currentPath?currentPath.split(".").reduce((v,k)=>v&&v[k],item)||{}:{}}
function populate(){const s=stance(),o=s.weaponOffset||[0,0];$("baseOffsetX").value=itemPartOffset[0]||0;$("baseOffsetY").value=itemPartOffset[1]||0;$("offsetX").value=o[0];$("offsetY").value=o[1];$("weaponRotation").value=s.weaponRotation||0;$("armRotation").value=s.armRotation||0;$("frontArmFrame").value=s.frontArmFrame||"";$("backArmFrame").value=s.backArmFrame||"";render()}
function update(){const s=stance();s.weaponOffset=[Number($("offsetX").value)||0,Number($("offsetY").value)||0];s.weaponRotation=Number($("weaponRotation").value)||0;s.armRotation=Number($("armRotation").value)||0;s.frontArmFrame=$("frontArmFrame").value||undefined;s.backArmFrame=$("backArmFrame").value||undefined;render()}
function nestedPartProperties(){item.animationCustom=item.animationCustom||{};item.animationCustom.animatedParts=item.animationCustom.animatedParts||{};item.animationCustom.animatedParts.parts=item.animationCustom.animatedParts.parts||{};const part=item.animationCustom.animatedParts.parts[itemPartName]=item.animationCustom.animatedParts.parts[itemPartName]||{};return part.properties=part.properties||{}}
function updateBase(){itemPartOffset=[Number($("baseOffsetX").value)||0,Number($("baseOffsetY").value)||0];if(itemPartOffsetSource==="baseOffset")item.baseOffset=[...itemPartOffset];else {nestedPartProperties().offset=[...itemPartOffset];itemPartOffsetSource="animationCustom"}if(generatedWeapon)generatedWeapon.baseOffset=[...itemPartOffset];setBaseInfo();render()}
function layer(data){if(!data||!data.image)return null;const image=new Image();image.src=data.image;return{image,frames:data.frames||null}}
function named(frames,name){if(!frames||!frames.frameGrid||!name)return null;let n=name,a=frames.aliases||{},seen={};while(a[n]&&!seen[n]){seen[n]=true;n=a[n]}const rows=frames.frameGrid.names||[];for(let y=0;y<rows.length;y++)for(let x=0;x<rows[y].length;x++)if(rows[y][x]===n)return{x,y};return null}
function first(frames){const rows=frames&&frames.frameGrid&&frames.frameGrid.names||[];for(let y=0;y<rows.length;y++)for(let x=0;x<rows[y].length;x++)if(typeof rows[y][x]==="string")return{x,y};return null}
function frame(sprite,name,fallback){if(!sprite||!sprite.image)return null;const data=sprite.frames||{},list=data.frameList;if(list){const r=list[name]||list[fallback]||list[Object.keys(list)[0]];return r?{x:r[0],y:r[1],w:r[2]-r[0],h:r[3]-r[1]}:{x:0,y:0,w:sprite.image.width,h:sprite.image.height}}const grid=data.frameGrid;if(!grid||!Array.isArray(grid.size))return{x:0,y:0,w:sprite.image.width,h:sprite.image.height};const pos=named(data,name)||named(data,fallback)||first(data);return pos?{x:pos.x*grid.size[0],y:pos.y*grid.size[1],w:grid.size[0],h:grid.size[1]}:{x:0,y:0,w:sprite.image.width,h:sprite.image.height}}
// Starbound 的角度以数学坐标（逆时针为正）表示；Canvas 的正角却是顺时针，故在此取反。
function draw(sprite,name,x,y,angle=0,scale=4,mirror=false,fallback="idle.1"){if(!sprite||!sprite.image.complete)return;const f=frame(sprite,name,fallback);ctx.save();ctx.translate(x,y);ctx.scale(mirror?-scale:scale,scale);ctx.rotate(-angle);ctx.drawImage(sprite.image,f.x,f.y,f.w,f.h,-f.w/2,-f.h/2,f.w,f.h);ctx.restore()}
// .frames 的每个 humanoid 图层都以相同的 43×43 原点对齐；旋转中心来自 humanoid.config，
// 不能把贴图中心或胸部位置当作肩膀。
function drawArm(sprite,name,root,rotationCenter,angle,mirror,fallback){if(!sprite||!sprite.image.complete)return;const f=frame(sprite,name,fallback),cx=Number(rotationCenter[0])||0,cy=Number(rotationCenter[1])||0,pivotX=f.w/2+cx,pivotY=f.h/2-cy;ctx.save();ctx.translate(root.x+facing*cx*PoseModel.scale,root.y-cy*PoseModel.scale);ctx.scale(mirror?-PoseModel.scale:PoseModel.scale,PoseModel.scale);ctx.rotate(-angle);ctx.drawImage(sprite.image,f.x,f.y,f.w,f.h,-pivotX,-pivotY,f.w,f.h);ctx.restore()}
// 武器 stance 只支配手臂；静态预览中的躯干始终保持站立帧，不能跟随 swim/run 手臂帧。
function bodyFrame(){return "idle.1"}
function screenVector(x,y,angle,mirror){const c=Math.cos(angle),s=Math.sin(angle),rx=c*x-s*y,ry=-s*x-c*y;return{x:mirror?-rx:rx,y:ry}}
function rotateGame(point,angle){const c=Math.cos(angle),s=Math.sin(angle);return{x:c*point.x-s*point.y,y:s*point.x+c*point.y}}
// 与 weapon.lua 相同：先 translate weaponOffset，再绕 weaponRotationCenter 旋转；最后由 Humanoid 绕肩部转动。
function weaponAnchor(hand,armAngle,weaponRotation,partOffset,stanceOffset,rotationCenter){const center={x:Number(rotationCenter[0])||0,y:Number(rotationCenter[1])||0},local={x:(Number(partOffset[0])||0)+(Number(stanceOffset[0])||0)-center.x,y:(Number(partOffset[1])||0)+(Number(stanceOffset[1])||0)-center.y},rotated=rotateGame(local,weaponRotation),group={x:center.x+rotated.x,y:center.y+rotated.y},v=screenVector(group.x*PoseModel.unitPixels,group.y*PoseModel.unitPixels,armAngle,facing<0);return{x:hand.x+v.x,y:hand.y+v.y}}
function configPoint(root,point,center,angle){const cx=Number(center[0])||0,cy=Number(center[1])||0,px=Number(point[0])||0,py=Number(point[1])||0,pivot={x:root.x+facing*cx*PoseModel.scale,y:root.y-cy*PoseModel.scale},v=screenVector((px-cx)*PoseModel.scale,(py-cy)*PoseModel.scale,angle,facing<0);return{x:pivot.x+v.x,y:pivot.y+v.y}}
function drawGeneratedWeapon(hand,angle,rotation,stanceOffset){if(!generatedWeapon)return;const parts=generatedWeapon.parts.filter(p=>p&&p.image&&p.image.complete);if(!parts.length)return;const total=parts.reduce((n,p)=>n+p.image.width,0),base=generatedWeapon.baseOffset||[0,0];let cursor=0;for(const part of parts){const localX=(cursor+part.image.width/2-total/2)*PoseModel.scale+((Number(base[0])||0)+(Number(stanceOffset[0])||0))*PoseModel.unitPixels,localY=((Number(base[1])||0)+(Number(stanceOffset[1])||0))*PoseModel.unitPixels,v=screenVector(localX,localY,angle+rotation,facing<0);draw(part,"",hand.x+v.x,hand.y+v.y,angle+rotation,PoseModel.scale,facing<0,"");cursor+=part.image.width}}
function render(){syncCanvas();ctx.clearRect(0,0,scene.width,scene.height);ctx.strokeStyle="#1d2c3f";for(let n=0;n<scene.width;n+=32){ctx.beginPath();ctx.moveTo(n,0);ctx.lineTo(n,scene.height);ctx.stroke()}for(let n=0;n<scene.height;n+=32){ctx.beginPath();ctx.moveTo(0,n);ctx.lineTo(scene.width,n);ctx.stroke()}const p=PoseModel,s=stance(),root={x:scene.width/2,y:scene.height*0.556},ar=(Number(s.armRotation)||0)*Math.PI/180,wr=(Number(s.weaponRotation)||0)*Math.PI/180,o=s.weaponOffset||[0,0],rotationCenter=s.weaponRotationCenter||[0,0],angle=aim+ar,frontCenter=humanoidConfig.frontArmRotationCenter||[-3,-1],backCenter=humanoidConfig.backArmRotationCenter||[-2,0],handPosition=humanoidConfig.frontHandPosition||[8,-3],shoulder=configPoint(root,frontCenter,frontCenter,0),hand=configPoint(root,handPosition,frontCenter,angle),weapon=weaponAnchor(hand,angle,wr,itemPartOffset,o,rotationCenter),frontFrame=s.frontArmFrame||"rotation",backFrame=s.backArmFrame||"rotation",twoHanded=Boolean(item&&item.twoHanded);drawArm(assets.backArm,twoHanded?backFrame:"idle.1",root,backCenter,twoHanded?angle:0,facing<0,"idle.1");draw(assets.body,bodyFrame(s),root.x,root.y,0,p.scale,facing<0);draw(assets.head,"normal",root.x,root.y,0,p.scale,facing<0,"normal");draw(assets.hair,"normal",root.x,root.y,0,p.scale,facing<0,"normal");draw(assets.face,"idle.1",root.x,root.y,0,p.scale,facing<0);if(generatedWeapon)drawGeneratedWeapon(hand,angle,wr,o);else draw(assets.item,"off",weapon.x,weapon.y,angle+wr,p.scale,facing<0,"off");drawArm(assets.frontArm,frontFrame,root,frontCenter,angle,facing<0,"rotation");if($("showGuides").checked){ctx.strokeStyle="#69c8ff";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(shoulder.x,shoulder.y);ctx.lineTo(shoulder.x+Math.cos(aim)*facing*140,shoulder.y-Math.sin(aim)*140);ctx.stroke();ctx.fillStyle="#ffae4a";ctx.beginPath();ctx.arc(hand.x,hand.y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#a7b3c5";ctx.fillText(t("bodyOrigin"),root.x+8,root.y+8)}}
async function preview(){if(!item)return;const data=await invoke("preview_assets",{root:$("root").value,activeitemPath:$("itemPath").value,species:$("species").value});humanoidConfig=data.humanoidConfig||{};itemPartOffset=Array.isArray(data.itemPartOffset)?data.itemPartOffset:[0,0];itemPartName=data.itemPartName||"middle";itemPartOffsetSource=data.itemPartOffsetSource||"animationCustom";$("baseOffsetX").value=itemPartOffset[0]||0;$("baseOffsetY").value=itemPartOffset[1]||0;setBaseInfo();generatedWeapon=data.generatedWeapon?{parts:(data.generatedWeapon.parts||[]).map(layer),baseOffset:data.generatedWeapon.baseOffset||[0,0]}:null;assets={};Object.entries(data).forEach(([key,value])=>{if(!["generatedWeapon","itemPartOffset","itemPartName","itemPartOffsetSource","humanoidConfig"].includes(key))assets[key]=layer(value)});const all=[...Object.values(assets),...(generatedWeapon?generatedWeapon.parts:[])];await Promise.all(all.filter(v=>v&&v.image).map(v=>v.image.decode?v.image.decode().catch(()=>{}):Promise.resolve()));render()}
async function load(){try{item=await invoke("load_activeitem",{path:$("itemPath").value});const paths=await invoke("find_stances",{value:item}),select=$("stance");select.innerHTML="";paths.forEach(p=>select.add(new Option(p,p)));currentPath=paths[0];select.value=currentPath||"";populate();await preview();statusKey("loaded",{count:paths.length,kind:t(generatedWeapon?"randomTemplate":"fixedTemplate")})}catch(e){status(String(e),true)}}
$("browseRoot").onclick=async()=>{const path=await invoke("choose_starbound_root");if(path){$("root").value=path;statusKey("rootSelected")}};$("browseItem").onclick=async()=>{const path=await invoke("choose_activeitem");if(path){$("itemPath").value=path;await load()}};$("stance").onchange=e=>{currentPath=e.target.value;populate()};$("flip").onclick=()=>{facing*=-1;render()};$("species").onchange=preview;$("showGuides").onchange=render;$("language").onchange=e=>{uiLanguage=e.target.value;try{localStorage.setItem("itemPoseEditor.language",uiLanguage)}catch(_){ }applyLanguage()};fields.forEach(id=>$(id).addEventListener("input",update));baseFields.forEach(id=>$(id).addEventListener("input",updateBase));canvas.addEventListener("pointermove",e=>{if(e.buttons!==1)return;const r=canvas.getBoundingClientRect(),rootX=r.width/2,rootY=r.height*.556,x=e.clientX-r.left-rootX,y=rootY-(e.clientY-r.top);aim=Math.atan2(y,x*facing);render()});(async()=>{applyLanguage();try{$("root").value=await invoke("default_root");statusKey("selectItem")}catch(e){status(String(e),true)}})();
